services:

  hello:
    container_name: 'hello'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./app:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
      - HTTP_HOST=0.0.0.0
    ports:
      - 'YOUR_MACHINE_PORT:8080'
    networks:
      - my_network

networks:
  my_network:
    external: true
